### ISSUE TITLE
Cannot switch between same page with different params

### ISSUE THREAD

**Issue by matthewlehner** [azicchetti/jquerymobile-router#1]
It looks like there's no easy way to switch pages, like say we're currently on page /index.html#localpage?param=1 and the url changes to /index.html#/localpage?param=2, using your example page it will currently just switch back to the index div.

Any hints/suggestions, or is this currently a limitation?

**Comment by azicchetti** [comment]
Linking to the same page is a tough issue, because jquery mobile basically ignores links to the active page.
However, it's possible to support this kind of links which may prove really useful in certain circumstances.

I've patched the source and added an example file, please check it out and let me know if this solves your issue.
