### ISSUE TITLE
Backbone.js example and usage of bc vs. bs

### ISSUE THREAD

**Issue by RainerAtSpirit** [azicchetti/jquerymobile-router#19]
Thanks for this excellent example! 
I'm wondering if there's a way to support switching the event from bs to bc in order to support client side rendering of header and footer as well.
When using bs each click on a detail leads to a correctly detail page.
When using bc instead only the first click will be resolved, further clicks doesn't trigger the event and the first rendered page is called again instead.

Reading your explanation at https://github.com/azicchetti/jquerymobile-router/issues/6 indicates that this is the expected behavior, but maybe there's nevertheless a way :).

Rainer

**Comment by azicchetti** [comment]
Hi,
there are a couple of things you can do to render both the header and the footer, and as you've pointed out, the best way is to use the beforecreate or init event.

Just keep your usual beforeshow event bound to the detail renderer, and add this route (supposing you're using the 'array' syntax):

 { ".": { events: "bc", handler: "page" } }

This handler will be called once for every single page in your multipage template or ajax application (I also add the "rm" event in ajax apps in order to clean my models and views once a page gets automatically removed by jquery mobile).

If you can't get this to work, please post again and I'll push an example that could also be useful to other people.

Cheers
