### ISSUE TITLE
changePage triggers wrong events

### ISSUE THREAD

**Issue by brianantonelli** [azicchetti/jquerymobile-router#24]
Most of my app follows the multipage model but there are one or two edge cases when I do a changePage and refer to the page's DOM ID instead of its data URL. This works correctly with JQM but JQMR invokes the events for the previously loaded page due to the lack of a URL change.

Example:
1) Browser is at http://test.com/index.html (page ID = "index")
2) Browser navigates to http://test.com/index2.html
3) JS command: $.mobile.changePage($("#index"));
4) Page changes to index.html but URL remains at index2.html. All page show events are reinvoked for index2.html when the page change events fire.

I know this is a pretty weird scenario but just wanted to make sure that it got documented.

**Comment by azicchetti** [comment]
Hi,
I was aware that invoking changePage with a jquery object would lead to problems but I forgot to mention it in the documentation -_-", sorry.
This issue seem similar to the one posted by Alexis Kinsella a few hours ago.

Wouldn't it be possible to do:
var dst=$("page selector").jqmData("url");
$.mobile.changePage( dst.charAt(0)=="/"?dst:"#"+dst ); ?

I know it seems ugly but it should work...

I'm also puzzled by the mix of page ids and "ajax urls".
I did a couple of experiments with first jqm releases and they ended up in a pretty big mess. Hope they fixed the issues!

Please let me know if the jqmData() thing works for you.

**Comment by akinsella** [comment]
Hi Andrea,

By the way, when you change page using a jquery object, are you able to get the complete url ? For instance, is it possible to get url params after the hash with a jquery object ? (#myPage?page=2&size=25)

**Comment by azicchetti** [comment]
Hi,
parameters for "local" pages are not stored in the data-url property (although it is true for ajax pages).
That's why invoking changePage with a jquery object is not that useful in a multipage template.

For instance:
        $.mobile.changePage("#mypage?foo=bar&my=params")

is actually supported, while

```
    $.mobile.changePage( $("#mypage?foo=bar") )
```

obviously triggers a jquery mobile error.

However, I'm trying to add support for routes based on the data-url property of jquery mobile objects, since another user just reported an issue similar to this one.

I'm testing out a patch right now
