### ISSUE TITLE
1.1.0 RC1 breaks existing 1.0.1 app

### ISSUE THREAD

**Issue by RainerAtSpirit** [azicchetti/jquerymobile-router#28]
Just as a heads up. I swapped out 1.1.0 RC1 in an existing application, which broke functionality.
At a first glance it seems that none of the events are firing any longer. Going back to 1.0.1 for the time being.

Rainer

**Comment by azicchetti** [comment]
Hi,
I've tried the 1.1.0-rc.1 version with jquery 1.7.1 and everything seems to work fine (you had me scared to death for a while! eheh).

Could you please test again or provide an example?
Thank you

**Comment by RainerAtSpirit** [comment]
@azicchetti : Sorry for scaring you to death, that wasn't my intention.Just wanted to give a heads up of a potential issue.

As requested I've updated my require.js/backbone.js example to use 1.1.0RC1 https://github.com/RainerAtSpirit/jquerymobile-router/tree/1.1.0RC1-RequireJS-Backbone and all is  working as expected.

Good news is that jqm-router is still working, bad news is that something in my app code is preventing a successful upgrade.

Thanks for looking into it.

Rainer

**Comment by azicchetti** [comment]
Don't worry, I was just kidding!
It was important to test out the 1.1.0 preview before it's actually released, so that we have time to patch our code if necessary.

I've based a lot of work projects on jquery mobile, backbone, jqm router, the datebox plugin, photoswipe and a couple of persistence plugins, and when a new jquery mobile version is released it takes a while to test the whole stack anew.

I'm glad that someone can do these tests and report potential issues when I'm busy at work, so thank you again for your time, you're helping a lot.
