### ISSUE TITLE
Same page example

### ISSUE THREAD

**Issue by scruffian** [azicchetti/jquerymobile-router#54]
Hi

I am trying to change the content of my page based on passing some parameters to the router. I have been looking at the same page example, but I am having  a couple of problems:
1. I want to stop the default animation, so that the page doesn't fade in/out.
2. The page seems to lose its active state on the second time I navigate to it.

I wonder if I am doing this the wrong way?

Thanks
Ben

**Comment by azicchetti** [comment]
Hi,
in order to stop the default animation, the anchor you're using to link the page should contain the data-transition="none" attribute.

For example:

```
<a href="#yourpage?param=value2&param2=value2" data-transition="none">yourpage</a>
```

I'm afraid I don't get the second question, what do you mean for losing the active state? Something related to the ui-btn-active class of navbar buttons?

**Comment by scruffian** [comment]
brilliant, thank you. how stupid of me to have not realised! the other problem is fixed now with this too...
