### ISSUE TITLE
Not working on android browser

### ISSUE THREAD

**Issue by tdurand** [azicchetti/jquerymobile-router#59]
Hi, 

I'm facing a new issue, my project is doing great on my chrome browser and i started to test it on mobile and it's not working at all. 

The android browser shows up a blank page... I tried to debug it with weirne but i didn't succeed to get error log.

My code is here: https://github.com/tdurand/faq-app-client-mobile

And you can test it here (from you android browser and you desktop browser): http://tdurand.github.com/faq-app-client-mobile/

Any ideas...? 

Thanks a lot

PS: i have an android 2.3, i tried with opera mobile and it worked

**Comment by azicchetti** [comment]
Il 27/09/2012 12:05, Thibault Durand ha scritto:

> I'm facing a new issue, my project is doing great on my chrome browser
> and i started to test it on mobile and it's not working at all.

Hi,
I've tried the webpage on the android simulator and it says:

E/browser (  317): Console: SyntaxError: Parse error 
http://tdurand.github.com/faq-app-client-mobile/main/router.js:32
I/bro

Since it works on the iphone i guess it's just the "default" keyword 
that causes the parsing error.
Try changing the function name to defaultHandler or something like that.

Cheers,
    Andrea

**Comment by tdurand** [comment]
Thanks a lot andrea ;-).

2012/9/27 Andrea Zicchetti notifications@github.com
