### ISSUE TITLE
Unable to load a Page from pagebeforeload

### ISSUE THREAD

**Issue by aiwilliams** [azicchetti/jquerymobile-router#6]
In order to provide a client-side rendering of Page content, I want to observe `pagebeforeload` and receive the `event, data` parameters so that I may `event.preventDefault()` and then `data.deferred.resolve()`, as described in [Page load events](http://jquerymobile.com/demos/1.0/docs/api/events.html). Is there another way to achieve this without the event and data?

**Comment by azicchetti** [comment]
Il 25/11/2011 21:48, Adam Williams ha scritto:

> In order to provide a client-side rendering of Page content, I want to observe `pagebeforeload` and receive the `event, data` parameters so that I may `event.preventDefault()` and then `data.deferred.resolve()`, as described in [Page load events](http://jquerymobile.com/demos/1.0/docs/api/events.html). Is there another way to achieve this without the event and data?

I can add support for pagebeforeload and pageload events and also pass 
the full event to the handler.

However, to add content/widgets to a page using client side templating 
and rendering, the pagebeforeload event isn't probably the most suited one.
Please note that it's only available and meaningful in ajax 
applications, not multipage ones.

Pagebeforecreate is probably the best choice here.

If you really need pageload events, please post some example code so 
that we can work something out together.

Cheers,
    Andrea

**Comment by aiwilliams** [comment]
Thank you for considering this issue!

One of the issues I am dealing with is having the application run in an offline mode, therefore requiring us to download all resources on the first html page request. This means that we do not want to use the Single Page approach. We do not want to use the Multiple Page approach, either, as that would have us place every page in the single html document, thereby leaving those views in memory when we don't want them there, or when some views will never be shown to some users. As I read through the page events, it seemed to me that we want to use beforepageload since we are in effect loading a page and not creating it from the DOM. I hope by doing so we will see jQuery Mobile unload pages we navigate from.

Does this still seem wrong in your experience? Also, to get past page loading when not using Multiple Page, I suppose I would have to turn off the ajax loading. If that is done, will pagebeforecreate still be invoked?

**Comment by azicchetti** [comment]
Il 25/11/2011 22:49, Adam Williams ha scritto:

> One of the issues I am dealing with is having the application run in an offline mode, therefore requiring us to download all resources on the first html page request.

Ok, got it. This seems a standard jqm ajax application, but the html 
files are stored locally (on the phone in the www/ directory of the 
phonegap application or cached by the browser as prescribed by the 
manifest file).

> This means that we do not want to use the Single Page approach. We do not want to use the Multiple Page approach, either, as that would have us place every page in the single html document, thereby leaving those views in memory when we don't want them there, or when some views will never be shown to some users. As I read through the page events, it seemed to me that we want to use beforepageload since we are in effect loading a page and not creating it from the DOM. I hope by doing so we will see jQuery Mobile unload pages we navigate from.

Uhm, why not the single page mode?
You start from a simple html page, jqm will automatically fetch other 
html pages and you'll add content to them. JQM will also remove them 
from the dom when the user navigates away.

When I'm about to write a dynamic ajax application in jqm I think of 
html _files_ as just the "skeleton" of the resulting ones. The client 
(backbone views bound to models) is responsible for adding the dynamic 
content, which may or may not need to be enhanced by jqm.

Hacking with pagebeforeload and pageload is only useful if you want to 
turn off the automatic ajax features of the framework and fetch the 
pages by yourself using $.ajax, a thing I would not recommend unless 
absolutely necessary.

> Does this still seem wrong in your experience? Also, to get past page loading when not using Multiple Page, I suppose I would have to turn of the ajax loading. If that is done, will pagebeforecreate still be invoked?

Yep, I think that the event would still fire, but the goal you're trying 
to achieve (clean dom, a few pages loaded at the same time, etc) can be 
obtained using the native features offered by the jqm framework.

Keep it simple until you can (at least in your navigation model), 'cause 
things may get really complicated very soon in other areas when you're 
building non-trivial applications

For example:
- internet is missing
- your models fail to load and need to be re-fetched while alerting the user
- the views need fallback content stored on the phone to provide a 
  minimal user-experience so that your app can pass apple's review
- javascript files [google maps?] must be loaded on demand and the views 
  must wait until their initialization is complete even if the model is 
  already available
- etc...
  These are the things that I find really complicated and also fascinating 
  during the development of mobile applications in javascript ;)

Back on topic, if you need an example using this technique I think I can 
help you with something.

Cheers,
    Andrea

**Comment by aiwilliams** [comment]
Hmmm, looks like `pagebeforeload` is not even called when I have an anchor like "#next" and no embedded Page. This appears to mean that I must use `pagebeforechange`, which is invoked even if the content is not in the DOM already. This is feeling very messy. I just read in the jQM source code how `pageremove` works, and it does not, with casual reading, appear to actually manage removing any page that is not loaded using AJAX.

In scouring the jQuery Mobile forums, I found that many people were looking to do client-side rendering. I did not find anything, based on what I have learned, that seemed like a good solution. I'm starting to think I might be better off using Backbone.Router with .page() enhancement. [This article](http://msdn.microsoft.com/en-us/scriptjunkie/hh377172) charges forward as if it's the way to go, but sadly the subsequent discussion of actually integrating jQM has yet to be written!

**Comment by aiwilliams** [comment]
Andrea, I failed to refresh before your response! You have been so helpful. I hadn't thought of the manifest file. I'll look into that more.

I would certainly like to keep it simple, but until I understand and have a functioning prototype that caches all the view resources, I don't feel I can charge forward building the actual application. Are you a freelance developer willing to consult a bit for pay? I shall not continue to submit issues that aren't issues for your code :)

**Comment by azicchetti** [comment]
Il 25/11/2011 23:49, Adam Williams ha scritto:

> Hmmm, looks like `pagebeforeload` is not even called when I have an anchor like "#next" and no embedded Page. This appears to mean that I must use `pagebeforechange`, which is invoked even if the content is not in the DOM already. This is feeling very messy. I just read in the jQM source code how `pageremove` works, and it does not, with casual reading, appear to actually manage removing any page that is not loaded using AJAX.

I'll try to sum up a couple of useful things with events, hope you can 
find it useful:
- pagebeforeload/load are called only when a page is fetched with ajax. 
  These events are only useful if you want to fetch pages "by hand". 
  Nobody wants to do this in normal circumstances
- pagebeforecreate/create/init are called before/after the page is 
  initialized, for both ajax and singlefile-multipage templates (pages are 
  lazily enhanced, that is to say that if you have 10 pages in a multipage 
  template, enhancement occurs only when the page is visited for the first 
  time). These are the events you want to use _when your page must be 
  rendered JUST ONE TIME AND IT'S NOT REUSED_. This is the typical case of 
  an ajax application[1]
- pagebeforeshow/show are always called, you want to use these events 
  when you have a singlefile-multipage template and you're using 
  parameters in the hash part of the url
- pageremove is called only in ajax applications, when the page is 
  removed from the dom. You'll use this to clean view references if you 
  have them
- pagebeforehide/hide are always called. You use these to clean/empty 
  the dom and your view references in singlefile-multipage applications

By following these guidelines you'll hardly find any problem developing 
with jquerymobile and backbone.

> In scouring the jQuery Mobile forums, I found that many people were looking to do client-side rendering. I did not find anything, based on what I have learned, that seemed like a good solution. I'm starting to think I might be better off using Backbone.Router with .page() enhancement. [This article](http://msdn.microsoft.com/en-us/scriptjunkie/hh377172) charges forward as if it's the way to go, but sadly the subsequent discussion of actually integrating jQM has yet to be written!

No no, trust me, using hybrid solutions is not a good idea.
It's more than an year that I play with jqm and client-side rendering, 
and I've learnt that you need to do things the "jquerymobile" way. It's 
really a piece of cake.
Most people find it difficult because they try to force the framework 
into something it's not.

**Comment by aiwilliams** [comment]
Andrea, I believe I have come to be at peace with this recommendation ;-) I will update my example application to reflect this wisdom. Thanks again for your patient guidance.

**Comment by azicchetti** [comment]
Eheh, hope you've found your way out of this mess that is mobile development !
