### ISSUE TITLE
Best Practices for Doing Error Dialog?

### ISSUE THREAD

**Issue by jevy** [azicchetti/jquerymobile-router#8]
There's little information ANYWHERE on the best way to catch an error in the form and display a dialog.

When I press the "next" button on a page, it checks to see if a field has a valid value.  If it does, it sets the value on the model and allows the pagechange to continue as normal.  However, if the validation fails, I'd like to redirect to a custom error dialog popup.  I do this using the manual "changePage" method.  This issue is that the dialog comes up, but quickly changes to the next page as if there was no error.

I think the problem is I have no way to get a handle on the event to call the "preventDefault" method to stop going to the next page.  Am I on the right track?

Jevin

**Comment by azicchetti** [comment]
Il 29/11/2011 16:06, jevy ha scritto:

> There's little information ANYWHERE on the best way to catch an error in the form and display a dialog.
> 
> When I press the "next" button on a page, it checks to see if a field has a valid value.  If it does, it sets the value on the model and allows the pagechange to continue as normal.  However, if the validation fails, I'd like to redirect to a custom error dialog popup.  I do this using the manual "changePage" method.  This issue is that the dialog comes up, but quickly changes to the next page as if there was no error.
> 
> I think the problem is I have no way to get a handle on the event to call the "preventDefault" method to stop going to the next page.  Am I on the right track?

Yep, you're almost there!

You just have to bind a "click" event on the "next" button (I usually do 
this in the "events" hash of my backbone view).

If the validation fails, it calls e.preventDefault() so that the normal 
page transition won't happen.
It's ok to call changePage("#certainErrorDialog") by hand in this situation.

Please remember that when the user clicks "cancel" on the dialog and 
returns to the previous page, that "route" will be called again.
That is to say: if you're in the "#contactsForm" page and have a route 
bound to it, a transition will take place to go to the dialog page 
(#certainErrorDialog).
As a result, when the user returns to "#contactsForm", it will be seen 
as a new transition to #contactsForm. You may want to avoid executing 
the route in this situation by inspecting the "ui" object passed down to 
the handler with something like this:

---

if (ui.prevPage && ui.prevPage.hasClass("ui-dialog")){
    return

## }

Hope this helps.

Cheers,
    Andrea

**Comment by jevy** [comment]
Just about to try the special ui case you mentioned.  Something surprising:
1) I seem to have to calls both e.preventDefault() AND e.stopPropagation().  Not having one of the other doesn't seem to work.

**Comment by azicchetti** [comment]
Il 29/11/2011 20:08, jevy ha scritto:

> Just about to try the special ui case you mentioned.  Something surprising:
> 1) I seem to have to calls both e.preventDefault() AND e.stopPropagation().  Not having one of the other doesn't seem to work.

You're right, I just checked and stopPropagation() is absolutely 
necessary (you can replace it with "return false", though).

**Comment by jevy** [comment]
This isn't trivial stuff is it? :D

Thanks for your help!  It's working really well now.

Jevin

On Tue, Nov 29, 2011 at 4:31 PM, Andrea Zicchetti <
reply@reply.github.com

**Comment by azicchetti** [comment]
Il 29/11/2011 22:36, jevy ha scritto:

> This isn't trivial stuff is it? :D

Eheh, working with default jqm dialogs is much more painful/useless. 
I've lost my faith in them.

If you have to target tablets/ipads, you must write your own solution 
'cause default dialogs are really too ugly to be used effectively, 
they're like the poor man's version of a modal window.

**Comment by jevy** [comment]
I actually don't use the dialog feature. I just create a different view
with just an okay button that grabs the errors from the model.

Works pretty good now that you've got me sorted out.

J
On Nov 29, 2011 5:09 PM, "Andrea Zicchetti" <
reply@reply.github.com>
wrote:
